### ISSUE TITLE
Spoofing UserAgent triggers all applications

### ISSUE THREAD

**Issue by ZOASR** [fingerprintjs/external-protocol-flooding#10]
Spoofing the user agent triggers all apps (installed and not installed) on Brave , and stops completely on Firefox.

**Brave :**
`UserAgent: Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0`
> ![image](https://user-images.githubusercontent.com/44146518/118328850-8d4d0b80-b506-11eb-87c0-0b0f2914d261.png)

 **Firefox :**
`UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4433.0 Safari/537.36`
> ![image](https://user-images.githubusercontent.com/44146518/118329074-e1f08680-b506-11eb-9e29-40bc170b6ac5.png)

**I suspect it is because of `getBrowserFamily()`:**
https://github.com/fingerprintjs/external-protocol-flooding/blob/5a2be48e5b3d2aaa8a0e62d7e997506e6253443e/packages/client/src/detector/browser.ts#L1-L23

**Comment by spalt08** [comment]
Thanks! The demo should bypass the UA spoofing now.
