### ISSUE TITLE
About the "scheme flooding"?

### ISSUE THREAD

**Issue by wenyu-yu** [fingerprintjs/external-protocol-flooding#11]
I am a developer from China, and when I try to translate the term "scheme flooding", there seems to be no easy-to-understand answer, so I would like to ask how do I understand the term "scheme flooding"?Looking forward to your reply, thanks!

**Comment by anewuser** [comment]
>研究人員解釋，之所以稱為方案洪水漏洞，是因為其使用自定義URL方案（URL Scheme）作為攻擊媒介。
https://www.ithome.com.tw/news/144424

URI schemes: https://zh.wikipedia.org/wiki/統一資源標誌符方案
你也可以看看: https://zh.wikipedia.org/wiki/洪泛路由 ("flooding" in another IT context)

**Comment by wenyu-yu** [comment]
多谢兄弟

**Comment by wenyu-yu** [comment]
> > 研究人員解釋，之所以稱為方案洪水漏洞，是因為其使用自定義URL方案（URL Scheme）作為攻擊媒介。
> > https://www.ithome.com.tw/news/144424
> 
> URI schemes: [https://zh.wikipedia.org/wiki/統一資源標誌符方案](https://zh.wikipedia.org/wiki/%E7%B5%B1%E4%B8%80%E8%B3%87%E6%BA%90%E6%A8%99%E8%AA%8C%E7%AC%A6%E6%96%B9%E6%A1%88)
> 你也可以看看: [https://zh.wikipedia.org/wiki/洪泛路由](https://zh.wikipedia.org/wiki/%E6%B4%AA%E6%B3%9B%E8%B7%AF%E7%94%B1) ("flooding" in another IT context)

多谢兄弟

**Comment by spalt08** [comment]
@anewuser
Thanks for the help!
