### ISSUE TITLE
All Applications are incorrect.

### ISSUE THREAD

**Issue by B2H990** [fingerprintjs/external-protocol-flooding#16]
Of all 23 applications it claims I have installed I have 0

![Screenshot from 2021-05-19 14-40-31](https://user-images.githubusercontent.com/67760966/118866652-36518880-b8b0-11eb-88cf-6a5e473f67a3.png)
.
![Screenshot from 2021-05-19 14-41-17](https://user-images.githubusercontent.com/67760966/118866723-49645880-b8b0-11eb-84b0-a05f0cc54177.png)

`This is your identifier. It was seen 986 times among 42201 tests so far.
That means it is 97.66% unique.
We have generated your identifier based on 23 applications you have installed.`

**Comment by spalt08** [comment]
Duplicate #5
