### ISSUE TITLE
False Positive: Spotify and Skype found, although they are not (and never were) installed

### ISSUE THREAD

**Issue by ccoenen** [fingerprintjs/external-protocol-flooding#18]
This machine I'm working on has been set up from scratch in January. I know very precisely what is installed right now and that I have never had Spotify or Skype installed.

When running this on Windows 10, with Firefox 88.0.1, this is my result:

![three apps installed](https://user-images.githubusercontent.com/124909/120018451-78cd4080-bfe7-11eb-8c90-e8657726269b.png)

**Comment by darthnithin** [comment]
I tested firefox 88.0.1 and Spotify (which isn't installed) is correctly not detected for me. Try going to skype://test see if it does anything.

**Comment by ccoenen** [comment]
This window comes up:

![grafik](https://user-images.githubusercontent.com/124909/120119532-71996480-c198-11eb-82f8-9457705806e0.png)

And when I click "Link öffnen" ("open link") then this happens:

![2021-05-30 22_42_48-skype___test_](https://user-images.githubusercontent.com/124909/120119537-837b0780-c198-11eb-8f44-66566b367f5b.png)

Telling me that nothing can react to `skype://` links.

**Comment by darthnithin** [comment]
Is it possible you _had_ skype installed at one point?

**Comment by ccoenen** [comment]
I certainly never installed either one. But if they'd have been preinstalled I would probably have removed them by now.

**Comment by spalt08** [comment]
May be related to #8 
Can you look into your windows registry, please? Might be located at `HKEY_CLASSES_ROOT/skype`

**Comment by ccoenen** [comment]
![grafik](https://user-images.githubusercontent.com/124909/120172662-91b23d80-c203-11eb-97fa-4bc940439a2d.png)

spotify also has a similar entry, there.

**Comment by spalt08** [comment]
Duplicates #8
