### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by MaxMatti** [fingerprintjs/external-protocol-flooding#7]
I get three different Fingerprints for Firefox, Chromium and Tor Browser (all three with supposedly vulnerable versions according to your README file). All three manage to miscalculate the apps that are installed. Firefox reports almost every app as installed (although I don't have all the reported ones) while the other two browsers report fewer apps installed than what's present on my pc. Running Archlinux with a few typical privacy-preserving Add-Ons on Firefox and an Adblocker on Chromium.

I can send you more exact information about my setup if you're interested, but I don't want to post that publicly.

I would be interested to see what part of my setup "breaks" the detection.

**Comment by spalt08** [comment]
Hi Max, Thanks for the feedback. 

Feel free to contact me on **konstantin.darutkin@fingerprintjs.com**

Will mark it as duplicate of #5
